theme: osuny
_merge: deep
pagination:
  pagerSize: 100
params:
  blocks:
    ignored: "block-class-cover"
  summary:
    position: hero
  search:
    active: false
  breadcrumb:
    position: none
  i18n:
    positions:
      - footer
  categories:
    single:
      taxonomies:
        display: true
  projects:
    index:
      options:
        categories: false
        summary: false
    single:
      taxonomies:
        position: hero
        show_name: true
    share_links:
      enabled: false
  image_sizes:
    design_system:
      lightbox:
        disabled: true
    blocks:
      image:
        desktop:  1964
      gallery:
        grid:
          desktop:  978
        large:
          desktop:  1964
    sections:
      projects:
        hero_single:
          mobile: 600
          desktop: 1964
          desktop: 1964
        layouts:
          grid:
            mobile:  500
            tablet:  1964
            desktop:  1964