theme: osuny
_merge: deep
pagination:
  pagerSize: 100
params:
  blocks:
    ignored: "block-class-cover"
  summary:
    position: hero
  search:
    active: false
  i18n:
    positions:
      - footer
  projects:
    index:
      options:
        categories: false
        summary: false
    single:
      taxonomies:
        position: hero
        show_name: true
    share_links:
      enabled: false
  image_sizes:
    design_system:
      lightbox:
        disabled: true
    blocks:
      image:
        desktop:  1964
        
      gallery:
        grid:
          desktop:  978
        large:
          desktop:  1964
    sections:
      projects:
        hero_single:
          desktop:  1729
        grid:
          desktop:  1904